server.port=8081
intershop.validation-url=https://host:9443/INTERSHOP/rest/BOS/DailyFreshFood-Site/B1/customersegments
intershop.accept-header=application/vnd.intershop.admin.customer_segments.v1+json